export const productData = [
  {
    id: "1",
    title: "Product1",
    description: "Producut1 description ",
    price: 200,
    quantity: 0,
    stock: 20,
    isVisible: true,
    imageUrl: "/honey.jpeg",
  },
  {
    id: "2",
    title: "Coffee Beans",
    description: "Premium dark roast coffee beans with a bold flavor.",
    price: 150,
    quantity: 0,
    stock: 20,
    isVisible: true,
    imageUrl: "/honey.jpeg",
  },

  {
    id: "3",
    title: "Wireless Headphones",
    description: "Noise-cancelling wireless headphones for immersive audio.",
    price: 850,
    quantity: 0,
    stock: 20,
    isVisible: false,
    imageUrl: "/honey.jpeg",
  },

  {
    id: "4",
    title: "Succulent Plant",
    description: "Easy-care succulent in a ceramic pot.",
    price: 75,
    quantity: 0,
    stock: 20,
    isVisible: true,
    imageUrl: "/honey.jpeg",
  },

  {
    id: "5",
    title: "Graphic T-Shirt",
    description: "Soft cotton t-shirt with a unique graphic design.",
    price: 175,
    quantity: 0,
    stock: 20,
    isVisible: true,
    imageUrl: "/honey.jpeg",
  },
];
